"$schema" = 'https://starship.rs/config-schema.json'

[hostname]
ssh_only = true
format = "[$hostname]($style) "
trim_at = "-"
style = "bold green"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[directory]
style = "cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = "branch "
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"
stashed = "#"
modified = "~"
staged = "+"
untracked = "?"
renamed = "r"
deleted = "x"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
min_time = 500
format = "[$duration]($style) "
style = "yellow"

[aws]
disabled = true

[nodejs]
symbol = "node "
format = "[$symbol($version )]($style)"

[python]
symbol = "py "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = "rs "
format = "[$symbol($version )]($style)"

[package]
symbol = "pkg "

[docker_context]
symbol = "docker "
format = "[$symbol$context]($style) "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[username]
style_user = "bold blue"
show_always = false

[container]
disabled = true
